export {
  loadGameSave,
  saveGameSave,
  getOrCreateGameSave,
  updateLevelProgress,
  getLevelProgress,
  setSelectedWeapon,
  getSelectedWeaponId,
  clearSaveData,
  getTotalStars,
  getPackStars,
  getPackMaxStars,
  isLevelUnlocked,
  getUnlockedLevels,
  getGameSettings,
  updateGameSettings,
  getRealismScaling,
  CURRENT_SCHEMA_VERSION,
} from './localStore';
export type { GameSave, LevelProgress, GameSettings, RealismPreset } from './localStore';
