export {
  loadGameSave,
  saveGameSave,
  getOrCreateGameSave,
  updateLevelProgress,
  getLevelProgress,
  setSelectedWeapon,
  getSelectedWeaponId,
  clearSaveData,
  getTotalStars,
  getPackStars,
  getPackMaxStars,
  isLevelUnlocked,
  getUnlockedLevels,
  getGameSettings,
  updateGameSettings,
  getRealismScaling,
  getTurretState,
  updateTurretState,
  resetTurretStateForWeapon,
  getZeroProfile,
  saveZeroProfile,
  deleteZeroProfile,
  getZeroDistance,
  getZeroRangeShotLimitMode,
  setZeroRangeShotLimitMode,
  getSelectedAmmoId,
  setSelectedAmmoId,
  getTutorialsSeen,
  markTutorialSeen,
  hasTutorialBeenSeen,
  clearTutorialsSeen,
  CURRENT_SCHEMA_VERSION,
} from './localStore';
export type { GameSave, LevelProgress, GameSettings, RealismPreset, TurretState, ZeroProfile, ZeroRangeShotLimitMode } from './localStore';
